version: '3.7'

services:
  db:
    image: postgres 
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"

      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"